{
    "branch": "master",
    "verifyConditions": {                                                                                                                             
        "path": "semantic-release-docker",
        "registryUrl": "docker.io"                                                                                                                    
    },             
    "plugins": [
        "commitizen",
        "@semantic-release/commit-analyzer",
        "@semantic-release/release-notes-generator",
        [
            "@semantic-release/changelog",
            {
                "changelogFile": "CHANGELOG.md",
                "changelogTitle": "# MBARI CUDA Deinterlace Changelog"
            }
        ],
        [
            "@semantic-release/git",
            {
                "assets": [
                    "CHANGELOG.md"
                ]
            }
        ],
        "semantic-release-docker",                                                                                                                    
        [                                                                                                                                             
            "@semantic-release/exec",                                                                                                                 
            {                                                                                                                                         
                "prepareCmd": "docker build --build-arg TAG=9.0-devel-ubuntu16.04 -t mbari/cuda-deinterlace:9.0 ."
            }                                                                                                                                         
        ],                                                                                                                                            
    ],                                                                                                                                                
    "publish": [                                                                                                                                      
        {                                                                                                                                             
            "path": "semantic-release-docker",                                                                                                        
            "name": "mbari/cuda-deinterlace:9.0"
         }                                                                                                                                             
    ] 
}
