{
    "branch": "master",
    "verifyConditions": {                                                                                                                             
        "path": "semantic-release-docker",
        "registryUrl": "docker.io"                                                                                                                    
    },             
    "plugins": [
        "commitizen",
        "@semantic-release/commit-analyzer",
        "@semantic-release/release-notes-generator",
        [
            "@semantic-release/changelog",
            {
                "changelogFile": "CHANGELOG.md",
                "changelogTitle": "# MBARI CUDA Deinterlace Changelog"
            }
        ],
        [
            "@semantic-release/git",
            {
                "assets": [
                    "CHANGELOG.md"
                ]
            }
        ]
    ]                                                                                                                                                
}
